export const Language = [
    { 
        name: 'spanish',
        setting:  {
            selectColumns: 'Seleccionar Columnas',
            filterResults: 'Filtrar resultados',
            rows: 'Filas',
            row: 'Fila',
            emptyMessage: 'No se encontro ningún resultado',
            selectAll: 'Marcar Todas',
            unSelectAll: 'Desmarcar Todas',
            search: 'Buscar',
            generated: 'Generada',
            total: 'Total',
            avarage: 'Media',
            maximum: 'Máximo',
            minimum: 'Mínimo',
            deleteRow: 'Eliminar fila',
            close: 'Cerrar',
            save: 'Guardar',
            column: 'Columna',
            columns: 'Columnas',
            show: 'Mostrar',
            fix: 'Fijar',
            name: 'Nombre',
            predefinedContent: 'Contenido predefinido',
            position: 'Posición',
            newPosition: 'Nueva posición',
            editable: 'Editable',
            applyFunction: 'Aplicar función',
            units: 'Ud.',   
            accept: 'Aceptar',
            configureFilter: 'Configurar filtro',
            closeConfigure: 'Cerrar configuración',
            configureColumns: 'Configurar columnas',
            editColumn: 'Editar columna',
            newColumn: 'Nueva columna',
            deleteColumn: 'Eliminar columna',
            export: 'Exportar',
            maximize: 'Maximizar',
            restore: 'Restaurar',
            visualize: 'Visualizar',
            matchWholeWord: 'Palabra exacta',
            matchCase: 'Distinción entre mayusculas y minúsculas',
            filterByColumns: 'Filtro por columnas',
            allOptions: 'Todas las opciones',
            active: 'Activo',
            edit: 'Editar',
            readMore: 'Ver más'
        }
    },
    {   
        name: 'english',
        setting:  {
            selectColumns: 'Select Columns',
            filterResults: 'Filter results',
            rows: 'Rows',
            row: 'Row',
            emptyMessage: 'No data to display',
            selectAll: 'Select All',
            unSelectAll: 'UnSelect All',
            search: 'Search',
            generated: 'Generated',
            total: 'Total',
            avarage: 'Average',
            maximum: 'Maximum',
            minimum: 'Minimum',
            deleteRow: 'Delete row',
            close: 'Close',
            save: 'Save',
            column: 'Column',
            columns: 'Columns',
            show: 'Show',
            fix: 'Fix',
            name: 'Name',
            predefinedContent: 'Predefined content',
            position: 'Position',
            newPosition: 'New position',
            editable: 'Editable',
            applyFunction: 'Apply function',
            units: 'Unit',   
            accept: 'Accept',
            configureFilter: 'Configure filter',
            closeConfigure: 'Close setting',
            configureColumns: 'Configure column',
            editColumn: 'Edit columns',
            newColumn: 'New column',
            deleteColumn: 'Delete column',
            export: 'Export',
            maximize: 'Maximize',
            restore: 'Restore',
            visualize: 'Visualize',
            matchWholeWord: 'Match whole word',
            matchCase: 'Match case',
            filterByColumns: 'Filter by columns',
            allOptions: 'All options',
            active: 'Active',
            edit: 'Edit',
            readMore: 'Read More'
        }
    }

];